name: Recent Pull Requests
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JamesIves/github-pages-deploy-action@v4
